# Generated by Django 3.0.4 on 2020-03-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_playlist', '0002_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='url',
            field=models.TextField(default='#', max_length=100),
        ),
    ]
