# Generated by Django 3.0.4 on 2020-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_playlist', '0003_latest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_playlist',
            name='url',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
